'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by hand to mirror what the Visual Studio Web
'     Forms designer produces for DDR_Developer.aspx. If you edit the .aspx
'     markup, regenerate/update this file to match the new control tree.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class DDR_Developer

    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    Protected WithEvents lblProject As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblContext As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblRef As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblDiscipline As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblDocMode As Global.System.Web.UI.WebControls.Label

    Protected WithEvents btnHome As Global.System.Web.UI.WebControls.LinkButton

    Protected WithEvents ctd_ddr_match As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents CTDDDRSOURCE As Global.System.Web.UI.WebControls.SqlDataSource

    Protected WithEvents DDR1 As Global.System.Web.UI.WebControls.LinkButton

    Protected WithEvents hfSelectedRow As Global.System.Web.UI.WebControls.HiddenField

    Protected WithEvents litProject As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDiscipline As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litRef As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents btnCtdPrev As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents btnCtdNext As Global.System.Web.UI.WebControls.LinkButton

    Protected WithEvents litKpiCtdHours As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litKpiDdrHours As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents lblKpiVariance As Global.System.Web.UI.WebControls.Label
    Protected WithEvents litKpiRowCount As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents lblKpiMatchStatus As Global.System.Web.UI.WebControls.Label

    Protected WithEvents pnlValidationSummary As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litValidationErrors As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents CTD_Grid As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents CTD_Source As Global.System.Web.UI.WebControls.SqlDataSource

    Protected WithEvents Plip_Search As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents CSV_Template As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents fuCsv As Global.System.Web.UI.WebControls.FileUpload
    Protected WithEvents CSV_Upload As Global.System.Web.UI.WebControls.LinkButton

    Protected WithEvents btnAddDDR As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnSaveAll As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnAllocateHours As Global.System.Web.UI.WebControls.Button

    Protected WithEvents grdDDREntry As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents CTD_Search_Source As Global.System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents RamzSource As Global.System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents AreaSource As Global.System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents PLIPSource As Global.System.Web.UI.WebControls.SqlDataSource

    Protected WithEvents updPLIP As Global.System.Web.UI.UpdatePanel
    Protected WithEvents txtSearchPLIP As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents gvPLIPSearch As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    Protected WithEvents ctdGrid As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents hfMultiplyRow As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents litMultiplyTarget As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents rblMultiplyMode As Global.System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents txtMultiplyCount As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnApplyMultiplier As Global.System.Web.UI.WebControls.Button

End Class
