'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool (normally by Visual Studio when the
'     .aspx file is saved). Included here so the sample compiles standalone;
'     if you open this in Visual Studio you can delete it and let VS
'     regenerate it from ParentPage.aspx instead.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace AspNetSmartSearch

    Partial Public Class ParentPage

        Protected WithEvents frmParent As System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents txtCustomerName As System.Web.UI.WebControls.TextBox
        Protected WithEvents btnSearchCustomer As System.Web.UI.WebControls.Button
        Protected WithEvents hfCustomerId As System.Web.UI.WebControls.HiddenField
        Protected WithEvents btnSave As System.Web.UI.WebControls.Button
        Protected WithEvents lblStatus As System.Web.UI.WebControls.Label

    End Class

End Namespace
