'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool (normally by Visual Studio when the
'     .aspx file is saved). Included here so the sample compiles standalone;
'     if you open this in Visual Studio you can delete it and let VS
'     regenerate it from SmartSearchDialog.aspx instead.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace AspNetSmartSearch

    Partial Public Class SmartSearchDialog

        Protected WithEvents frmSearch As System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents hfTargetTextClientId As System.Web.UI.WebControls.HiddenField
        Protected WithEvents hfTargetHiddenClientId As System.Web.UI.WebControls.HiddenField
        Protected WithEvents hfMode As System.Web.UI.WebControls.HiddenField
        Protected WithEvents txtSearch As System.Web.UI.WebControls.TextBox
        Protected WithEvents btnSearch As System.Web.UI.WebControls.Button
        Protected WithEvents lblMessage As System.Web.UI.WebControls.Label
        Protected WithEvents gvResults As System.Web.UI.WebControls.GridView

    End Class

End Namespace
