'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class SmartDDRv3

    Protected WithEvents frmSmartDDR As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    ' Sidebar
    Protected WithEvents ddlProjectGroup As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents Project_Summary As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents M75_AFC_ALL As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents IFR_ALL As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents PLIP_STATUS As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents DDR_ACT_ALL As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents DDLPROJNO As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents CTD As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents DDR1 As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents ACTIVITY As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents CTD_DDR As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents CTD_DOC As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents DDR_DUMMY As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents DDR2 As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents DDR_EPR As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents EPR As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents M75_AFC As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents IFR As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents Aconex1 As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents Aconex2 As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents ACON_MISS As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents PushtoDDR As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents Push As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkAdmin As Global.System.Web.UI.WebControls.HyperLink

    ' Header + toolbar
    Protected WithEvents lblSection As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblContext As Global.System.Web.UI.WebControls.Label
    Protected WithEvents LblInfo As Global.System.Web.UI.WebControls.Label
    Protected WithEvents LblWN As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    Protected WithEvents DDLDISCIPLINE As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnClearFilter As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblFilterChip As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblRowCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkDeepLink As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCSV As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    ' Content
    Protected WithEvents pnlGrid As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents MyCommonGrid As Global.System.Web.UI.WebControls.GridView

    ' Row actions + drawer
    Protected WithEvents hfRowArg As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents btnPushRow As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnDrawerCsv As Global.System.Web.UI.WebControls.Button
    Protected WithEvents updDrawer As Global.System.Web.UI.UpdatePanel
    Protected WithEvents btnDrill As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlDetails As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblDrawerTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblDrawerCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents grdDrawer As Global.System.Web.UI.WebControls.GridView

End Class
