'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

' The dashboard page has no server controls: the markup is a static shell and
' all data is fetched as JSON from the code-behind (?api=...).
Partial Public Class SmartDDRDashboard

End Class
