'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Admin_DDR_EditV2

    Protected WithEvents frmAdminDDR As Global.System.Web.UI.HtmlControls.HtmlForm

    ' Top bar
    Protected WithEvents LblInfo As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label
    Protected WithEvents imgLogo As Global.System.Web.UI.WebControls.Image

    ' Access denied
    Protected WithEvents pnlDenied As Global.System.Web.UI.WebControls.Panel

    ' Editor
    Protected WithEvents phApp As Global.System.Web.UI.WebControls.PlaceHolder
    Protected WithEvents DDLPROJNO As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents DDLDISCIPLINE As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnReload As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCSV As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    Protected WithEvents litGrid As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents hfKey As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents hfExportIds As Global.System.Web.UI.WebControls.HiddenField

End Class
